import { DEAD, ALIVE } from '../constants/constants';

export default [
  // doppio blinker
  [
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ]
  ],

  // toad
  [
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, ALIVE, ALIVE, ALIVE, DEAD, DEAD ],
    [ DEAD, DEAD, ALIVE, ALIVE, ALIVE, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ]
  ],

  // glider
  [
    [ DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ ALIVE, ALIVE, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ],
    [ DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD ]
  ]
];
